name: Docker Image CI

on:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: manangandhi1810/react-auth-template

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: linux/amd64,linux/arm64

            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
